language: python
python:
  - "2.7"
 # - "3.3"
env:
  - SUBLIME_TEXT_VERSION="2"
  - SUBLIME_TEXT_VERSION="3"
# command to install dependencies
install:
  # Install Sublime Text and output version
  - curl https://raw.githubusercontent.com/twolfson/sublime-installer/0.1.3/install.sh | sh -s $SUBLIME_TEXT_VERSION
  - subl --version

  # Install Railo
   - wget http://cfml-ci.s3.amazonaws.com/railo-express-4.2.1.000-nojre.tar.gz
   - tar -xvf railo-express-4.2.1.000-nojre.tar.gz
   - cd railo-express-4.2.1.000-nojre
   - ./start.sh

  # Install dev dependencies
  - pip install sublime-plugin-tests
  - pip install flake8
  - pip install pep257

  # Install our plugin
  - mkdir -p '~/.config/sublime-text-'$SUBLIME_TEXT_VERSION'/Packages/'
  - ln -s $PWD '~/.config/sublime-text-'$SUBLIME_TEXT_VERSION'/Packages/MXUnit'

before_script:
  # Generate a screen buffer to collect Sublime Text window
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Ensure the scripts self-terminate
  - export SUBLIME_AUTO_KILL=TRUE

# command to run tests
script:
  - flake8 *.py --max-line-length=120 --ignore="W191"
  - pep257 *.py

  # Run our tests
  - nosetests --nocapture --verbose --stop